### ISSUE TITLE
Maven error

### ISSUE THREAD

**Issue by lpsandaruwan** [thilinamh/PicknRide-test-maven#1]
I get this error, when I try to import the project into spring tool suit.

Could not calculate build plan: Plugin org.apache.maven.plugins:maven-resources-plugin:2.6 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-resources-plugin:jar:2.6
Plugin org.apache.maven.plugins:maven-resources-plugin:2.6 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-resources-plugin:jar:2.6

**Comment by thilinamh** [comment]
Does "mvn -v" command works?

**Comment by thilinamh** [comment]
Can you create a new maven project with STS?

**Comment by thilinamh** [comment]
Make sure you are connected to the Internet when you are importing the project for the first time. It needs to download several dependencies.
